insert into etiquettes (id, nom) values (1, 'Froid');
insert into etiquettes (id, nom) values (2, 'Chaud');
insert into etiquettes (id, nom) values (3, 'Jus');
insert into etiquettes (id, nom) values (4, 'Coktail');
insert into etiquettes (id, nom) values (5, 'Eau');
insert into etiquettes (id, nom) values (6, 'Poulet');
insert into etiquettes (id, nom) values (7, 'Boeuf');
insert into etiquettes (id, nom) values (8, 'Agneau');
insert into etiquettes (id, nom) values (9, 'Poisson');
insert into etiquettes (id, nom) values (10, 'Oeuf');
insert into etiquettes (id, nom) values (11, 'Vegetarien');
insert into etiquettes (id, nom) values (12, 'Vegan');
insert into etiquettes (id, nom) values (13, 'sucrer');
insert into etiquettes (id, nom) values (14, 'Sale');
insert into etiquettes (id, nom) values (15, 'Piquant');
insert into etiquettes (id, nom) values (16, 'Tres piquant');